#pragma once

#include <QObject>

#define	TS_WHILEDRILLINGDETECT	QObject::tr("While Drilling Detect")
#define TS_MENU                 QObject::tr(" Menu")
#define	TS_PROJECT              QObject::tr("Project")
#define	TS_NEW_PROJECT          QObject::tr("New Project")
#define	TS_OPEN_PROJECT         QObject::tr("Open Project")
#define	TS_IMPORT_PROJECT       QObject::tr("Import Project")
#define	TS_SAVE_CURRENT_PROJECT	QObject::tr("Save Current Project")
#define	TS_EXPORT_PROJECT       QObject::tr("Export Project")
#define	TS_EXIT                 QObject::tr("Exit")

#define TS_PROJECT_INFO         QObject::tr("Project Info")
#define TS_PROJECT_BASIC_INFO   QObject::tr("Bacic Info")
#define TS_PROJECT_PROGRESS     QObject::tr("Progress List")
#define TS_PROJECT_PROGRESS_INFO     QObject::tr("Progress Info")
#define TS_PROJECT_PROGRESS_STATION_INFO     QObject::tr("Station Info")
#define TS_PROJECT_PROGRESS_WORKSPACE_INFO     QObject::tr("Workspace Info")
#define TS_PROJECT_PROGRESS_WAVEFILTER_SETTINGS     QObject::tr("WaveFilter Settings")



#define TS_VIEW                 QObject::tr("View")

#define TS_TOOLBAR              QObject::tr(" Toolbar")
#define TS_DATA_SELECT          QObject::tr("Data Select")
#define TS_DATA_LOAD            QObject::tr("Load")
#define TS_WAVE_SHOW            QObject::tr("Wave Show")
#define TS_CORINTERFERENCE      QObject::tr("CorInterFerence")
#define TS_INVERSION_2DIMAGING  QObject::tr("Inversion_2DImaging")
#define TS_INVERSION_3DIMAGING  QObject::tr("Inversion_3DImaging")
#define TS_INVERSION_3DIMAGING_RIGHTDOCKWIDGET  QObject::tr("Inversion_3DImaging Setting")

#define TS_START_DATA_ACQUIRE   QObject::tr("Start DataAcquire")

#define TS_DETECTOR_NUM         QObject::tr("Detector Num")
#define TS_IMPORT               QObject::tr("Import")
#define TS_EXPORT               QObject::tr("Export")
#define TS_SELECT_ALL           QObject::tr("Select All")
#define TS_ADD                  QObject::tr("Add")
#define TS_DELETE               QObject::tr("Delete")
#define TS_SAMPLE_RATE          QObject::tr("Sample Rate")
#define TS_ID_DETECTOR_ID       QObject::tr("Detector Id")
#define TS_STATUS_HEADER_STATION_NAME    QObject::tr("Station Name")
#define TS_NORTH                QObject::tr("North")
#define TS_EAST                 QObject::tr("East")
#define TS_ELEVATION            QObject::tr("Elevation")
#define TS_SENSITIVITY          QObject::tr("Sensitity")
#define TS_SENSITIVITY_UNIT     QObject::tr("Sensitity Uint")
#define TS_ID_CHANNEL_ID        QObject::tr("Channel Id")
#define TS_IMPDET_ERR_CMPINFOHELP   QObject::tr("Cmpinfo Tip Info")
#define TS_WARNING              QObject::tr("Warning")
#define TS_OK                   QObject::tr("OK")

#define TS_PROJECT_NAME         QObject::tr("Project Name")
#define TS_CREATER              QObject::tr("Creater")
#define TS_PROJECT_START_TIME   QObject::tr("Project Start Time")
#define TS_PROJECT_DIR          QObject::tr("Project Dir")
#define	TS_BROWSE               QObject::tr("Browse")
#define	TS_REMARKS              QObject::tr("Remarks")
#define	TS_SEISMIC_SOURCE       QObject::tr("Seismic Source")
#define	TS_CANCEL               QObject::tr("Cancel")
#define	TS_SAVE                 QObject::tr("Save")
#define TS_DETECTOR_PARA        QObject::tr("detector para")
#define TS_DETECTOR_POSITION_MAP    QObject::tr("detector position map")
#define	TS_ID_DP_TABLE_THE	        QObject::tr("Detector para table the")
#define	TS_ROW	                QObject::tr("row")
#define	TS_THE              	QObject::tr("the")
#define	TS_ID_DEVICE	        QObject::tr("device")
#define	TS_COMPONENT	        QObject::tr("Component")
#define	TS_ID_MULTIPLE_USE	    QObject::tr("multiple use")
#define	TS_ID_ERR_DETECTOR_DEVICE	QObject::tr("the same detector, data acquisition must be the same")
#define	TS_STATION          	QObject::tr("station")
#define	TS_IMPDET_ERR_SAMPLE	QObject::tr("sample error")
#define	TS_IMPDET_ERR_UNCOMPLETE	QObject::tr("input not complete")
#define	TS_COL	                QObject::tr("col")
#define	TS_IMPDET_ERR_DATA	    QObject::tr("input data error")
#define	TS_ID_IMPORT_DETECTOR_PARA_ERROR	QObject::tr("import detector para error")
#define	TS_ID_EXPORT_DETECTOR_PARA_ERROR	QObject::tr("export detector para error")
#define	TS_ID_SELECT_ROW	QObject::tr("Select detector rows you need delete")
#define	TS_ID_IF_DELETE_SELECED_ROW	QObject::tr("If delete selected detector row")
#define TS_WORKSPACE_CAN_NOT_BE_EMPTY   QObject::tr("Workspace can not be empty")
#define TS_PROJECTINFO_CAN_NOT_BE_EMPTY     QObject::tr("Projectinfo can not be empty")
#define	TS_START_TIME	        QObject::tr("start time")
#define	TS_PROGRESS_NAME	    QObject::tr("progress name")
#define TS_PROGRESS_INFO_CAN_NOT_BE_EMPTY   QObject::tr("progress info can not be empty")
#define	TS_ADD_PROGRESS	        QObject::tr("add progress")
#define	TS_LOAD_WAVE            QObject::tr("load wave")
#define	TS_SELECT_LOAD_TIME     QObject::tr("please select data laod time")
#define TS_BANDPASS_FILTER      QObject::tr("bandpass filter")
#define TS_TRAP_FILTER          QObject::tr("trap filter")
#define TS_NOISE_FILTER         QObject::tr("noise filter")
#define TS_MINIMUM_FREQUENCY    QObject::tr("minimum frequency")
#define TS_MAXIMUM_FREQUENCY    QObject::tr("maximum frequency")
#define TS_SMOOTH_WIDTH         QObject::tr("smooth width")
#define TS_BP_FILTER_CAN_NOT_BE_EMPTY   QObject::tr("bp filter can not be empty")
#define	TS_MPARASETUP_MAX_FREQ_LESS_THAN_MIN_FREQ	QObject::tr("Band pass max freq cannot be less than min freq!")
#define	TS_BANDREJECT_FREQ      QObject::tr("bandpass frequency")
#define	TS_BAND_MULTIPLIER_COUNT   QObject::tr("bandpass multiplier count")
#define	TS_TRAP_FILTER_PARA_ERROR     QObject::tr("trap filter setting para error")
#define	TS_TRAP_FILTER_GROUP    QObject::tr("trap group")

#define	TS_ABOUT                QObject::tr("About")
#define	TS_SHORTCUTS            QObject::tr("Shortcuts")

#define TS_PROJECT_NAME_HAS_BEEN_EXIST  QObject::tr("This project has been existed!")
#define	TS_CREATE_DIR_FAILED    QObject::tr("create dir failed")
#define	TS_DELETE_PROJECT_FAILED    QObject::tr("delete project failed")
#define	TS_EXPORT_PROJECT_FAILED    QObject::tr("export project failed")
#define	TS_IMPORT_PROJECT_FAILED    QObject::tr("import project failed")
#define TS_COVERING             QObject::tr("Whether covering")
#define TS_IMPORT_PROJECT_ALREADY_EXIST    QObject::tr("import project already exist")
#define	TS_OPEN_PROJECT_FAILED   QObject::tr("Open Project Failed")
#define	TS_PROGRESS_NAME_ALREADY_EXIST   QObject::tr("progress name already exist")
#define TS_PREVIEW              QObject::tr("preview")
#define TS_OPEN                 QObject::tr("open")
#define TS_CLOSE                QObject::tr("close")
#define TS_NOISE                QObject::tr("noise")
#define TS_EFFECTIVE_WAVE       QObject::tr("effective wave")
#define TS_MINIMUM              QObject::tr("minimum")
#define TS_MAXIMUM              QObject::tr("maximum")

#define	TS_METER            	QObject::tr("Meter")
#define TS_TUNNEL_FACE_CENTER_EAST    QObject::tr("tunnel face center east")
#define TS_TUNNEL_FACE_CENTER_NORTH    QObject::tr("tunnel face center north")
#define TS_TUNNEL_FACE_CENTER_ELE    QObject::tr("tunnel face center ele")
#define TS_TUNNEL_FACE_FRONT_LEN    QObject::tr("tunnel face center front len")
#define TS_TUNNEL_FACE_BEHIND_LEN    QObject::tr("tunnel face center behind len")
#define TS_TUNNEL_FACE_WIDTH    QObject::tr("tunnel face width")
#define TS_TUNNEL_FACE_HEIGHT   QObject::tr("tunnel face height")
#define TS_TUNNEL_FACE_TOWARDS  QObject::tr("tunnel face towards")
#define TS_SPACE_GRID_STEP      QObject::tr("space grid step")
#define TS_WAVE_SPEED           QObject::tr("wave speed")

#define	TS_NP_PROJECT_NAME_PROMPT	QObject::tr("just support english")
#define TS_DEGREE               QObject::tr("degree")
#define TS_METER_PER_SECOND     QObject::tr("meter per second")
#define TS_ADD_PROGRESS_FAILED  QObject::tr("add progress failed")
